import type { Semester, SiteSettings, Subject } from "./types";

export const defaultSettings: SiteSettings = {
  homepageTitle: "BSc CSE Academic Portal",
  homepageSubtitle: "Semesters, routines, notices, course details, and Google Drive resources in one secure dashboard.",
  supportEmail: "shazidsaharia21@gmail.com",
};

export const seedSemesters: Semester[] = [
  { id: "semester-1", number: 1, title: "Semester 1", subtitle: "1st Year 1st Semester", totalCredits: 17.5 },
  { id: "semester-2", number: 2, title: "Semester 2", subtitle: "1st Year 2nd Semester", totalCredits: 20.5 },
  { id: "semester-3", number: 3, title: "Semester 3", subtitle: "2nd Year 1st Semester", totalCredits: 21.5 },
  { id: "semester-4", number: 4, title: "Semester 4", subtitle: "2nd Year 2nd Semester", totalCredits: 21 },
  { id: "semester-5", number: 5, title: "Semester 5", subtitle: "3rd Year 1st Semester", totalCredits: 21 },
  { id: "semester-6", number: 6, title: "Semester 6", subtitle: "3rd Year 2nd Semester", totalCredits: 23 },
  { id: "semester-7", number: 7, title: "Semester 7", subtitle: "4th Year 1st Semester", totalCredits: 19.5 },
  { id: "semester-8", number: 8, title: "Semester 8", subtitle: "4th Year 2nd Semester", totalCredits: 18 },
];

const d = (title: string) => `${title} from the Rabindra Maitree University BSc Engineering in Computer Science syllabus. Admins can expand this description, assign teachers, and connect the official Google Drive resource folder.`;
const s = (courseCode: string, courseTitle: string, semester: number, credits: number, description = d(courseTitle)): Omit<Subject, "id"> => ({ courseCode, courseTitle, semester, credits, description, teacher: "", driveLink: "" });

export const seedSubjects: Omit<Subject, "id">[] = [
  s("CSE 1101", "Introduction to Computer System", 1, 2, "Computer generations and classification, data representation, hardware and software components, operating systems, communication networks, Internet, HTML, and application software."),
  s("CSE 1102", "Programming Fundamentals", 1, 3, "Problem solving, algorithms, flowcharts, debugging, documentation, and C programming including control statements, functions, arrays, pointers, structures, files, preprocessors, libraries, and graphics."),
  s("CSE 1103", "Programming Fundamentals Lab I", 1, 1.5, "Laboratory works based on CSE 1102."),
  s("CHEM 1101", "Chemistry", 1, 2, "Atomic structure, chemical bonds, molecular structures, organic reactions, solutions, phase rule, dilute solutions, thermochemistry, kinetics, equilibria, ionization, and electrical properties of solution."),
  s("MATH 1101", "Differential Calculus and Co-ordinate Geometry", 1, 3, "Limits, continuity, differentiation, expansions, maxima and minima, partial differentiation, tangents, normals, conics, circles, parabola, ellipse, hyperbola, pole, polar, and related coordinate geometry topics."),
  s("GED 01", "Bangla Language", 1, 3),
  s("GED 02", "English I: Basic Communicative Skills", 1, 3, "Language and grammar, sentence construction, passive voice, conditionals, oral and writing skills, good writing style, speaking, and listening."),
  s("CSE 1201", "Discrete Mathematics", 2, 2),
  s("CSE 1202", "Object Oriented Programming using C++", 2, 3),
  s("CSE 1203", "Object Oriented Programming using C++ Lab", 2, 1.5),
  s("PHY 1201", "Physics", 2, 2),
  s("EEE 1201", "Introduction to Electrical Engineering", 2, 3),
  s("EEE 1202", "Introduction to Electrical Engineering Lab", 2, 1.5),
  s("EEE 1203", "Engineering Drawing", 2, 1.5),
  s("MATH 1201", "Integral Calculus, ODE, PDE, and Series Solutions", 2, 3),
  s("GED 03", "English II: Advanced Reading and Writing", 2, 3),
  s("CSE 2101", "Data Structures", 3, 2),
  s("CSE 2102", "Data Structures Lab", 3, 1),
  s("CSE 2103", "Digital Logic Design", 3, 3),
  s("CSE 2104", "Digital Logic Design Lab", 3, 1.5),
  s("EEE 2101", "Electronic Devices and Circuits", 3, 3),
  s("EEE 2102", "Electronic Devices and Circuits Lab", 3, 1.5),
  s("EEE 2103", "Basic Mechanical Engineering", 3, 2),
  s("MATH 2101", "Complex Variables and Matrices", 3, 3),
  s("CSE 2105", "Object Oriented Programming using Java", 3, 3),
  s("CSE 2106", "Object Oriented Programming using Java Lab", 3, 1.5),
  s("CSE 2201", "Algorithms", 4, 3),
  s("CSE 2202", "Algorithms Lab", 4, 1.5),
  s("CSE 2203", "Database Management System", 4, 3),
  s("CSE 2204", "Database Management System Lab", 4, 1.5),
  s("CSE 2205", "Computer Architecture", 4, 3),
  s("CSE 2206", "Data Communication", 4, 3),
  s("STAT 2201", "Statistics and Probability", 4, 3),
  s("MATH 2201", "Vectors, Fourier Analysis, and Laplace Transforms", 4, 3),
  s("CSE 3101", "Peripherals and Interfacing", 5, 3),
  s("CSE 3102", "Peripherals and Interfacing Lab", 5, 1.5),
  s("CSE 3103", "Software Engineering and Information System Design", 5, 3),
  s("CSE 3104", "Software Engineering and Information System Design Lab", 5, 1.5),
  s("CSE 3105", "Operating System", 5, 3),
  s("CSE 3106", "Numerical Methods", 5, 3),
  s("CSE 3107", "Technical Writing and Presentation", 5, 1),
  s("GED 04", "History of Emergence of Independent Bangladesh", 5, 3),
  s("BUS 3101", "Financial and Managerial Accounting", 5, 2),
  s("CSE 3201", "Mathematical Analysis for Computer Science", 6, 3),
  s("CSE 3202", "Theory of Computation", 6, 3),
  s("CSE 3203", "Computer Networks", 6, 3),
  s("CSE 3204", "Computer Networks Lab", 6, 1.5),
  s("CSE 3205", "Microprocessors and Microcontrollers", 6, 3),
  s("CSE 3206", "Assembly Language, Microprocessors and Microcontrollers Lab", 6, 1.5),
  s("CSE 3207", "Web Engineering", 6, 2),
  s("CSE 3208", "Web Engineering Lab", 6, 1),
  s("GED 08", "Socio-economic and Political Studies of Bangladesh", 6, 3),
  s("BUS 3201", "Professional Ethics and Industrial Management", 6, 2),
  s("CSE 4101", "Artificial Intelligence", 7, 3),
  s("CSE 4102", "Artificial Intelligence Lab", 7, 1.5),
  s("CSE 4103", "Compiler Design and Construction", 7, 3),
  s("CSE 4104", "Compiler Design and Construction Lab", 7, 1.5),
  s("CSE 4105", "Cryptography and Network Security", 7, 3),
  s("CSE 4106", "Cryptography and Network Security Lab", 7, 1.5),
  s("CSE 4107", "Simulation and Modeling", 7, 3),
  s("CSE 4108", "Computer Graphics", 7, 2),
  s("CSE 4109", "Computer Graphics Lab", 7, 1),
  s("CSE 4201", "Digital Signal and Image Processing", 8, 3),
  s("CSE 4202", "Project and Thesis", 8, 6),
  s("CSE-OPT1", "Optional Course 1", 8, 3),
  s("CSE-OPT1L", "Optional Course 1 Lab", 8, 1.5),
  s("CSE-OPT2", "Optional Course 2", 8, 3),
  s("CSE-OPT2L", "Optional Course 2 Lab", 8, 1.5),
];
